/*
Copyright Sparebanken Vest

Authored by The Cumulus Team.
*/

// Code generated by client-gen. DO NOT EDIT.

// This package contains the scheme of the automatically generated clientset.
package scheme
