/*
Copyright Sparebanken Vest

Authored by The Cumulus Team.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	azurekeyvaultcontrollerv1alpha1 "github.com/SparebankenVest/azure-keyvault-controller/pkg/apis/azurekeyvaultcontroller/v1alpha1"
	versioned "github.com/SparebankenVest/azure-keyvault-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/SparebankenVest/azure-keyvault-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/SparebankenVest/azure-keyvault-controller/pkg/client/listers/azurekeyvaultcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AzureKeyVaultSecretInformer provides access to a shared informer and lister for
// AzureKeyVaultSecrets.
type AzureKeyVaultSecretInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AzureKeyVaultSecretLister
}

type azureKeyVaultSecretInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAzureKeyVaultSecretInformer constructs a new informer for AzureKeyVaultSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAzureKeyVaultSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAzureKeyVaultSecretInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAzureKeyVaultSecretInformer constructs a new informer for AzureKeyVaultSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAzureKeyVaultSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzurekeyvaultcontrollerV1alpha1().AzureKeyVaultSecrets(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzurekeyvaultcontrollerV1alpha1().AzureKeyVaultSecrets(namespace).Watch(options)
			},
		},
		&azurekeyvaultcontrollerv1alpha1.AzureKeyVaultSecret{},
		resyncPeriod,
		indexers,
	)
}

func (f *azureKeyVaultSecretInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAzureKeyVaultSecretInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *azureKeyVaultSecretInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&azurekeyvaultcontrollerv1alpha1.AzureKeyVaultSecret{}, f.defaultInformer)
}

func (f *azureKeyVaultSecretInformer) Lister() v1alpha1.AzureKeyVaultSecretLister {
	return v1alpha1.NewAzureKeyVaultSecretLister(f.Informer().GetIndexer())
}
