/*
Copyright Sparebanken Vest

Authored by The Cumulus Team.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/SparebankenVest/azure-keyvault-controller/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// AzureKeyVaultSecrets returns a AzureKeyVaultSecretInformer.
	AzureKeyVaultSecrets() AzureKeyVaultSecretInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// AzureKeyVaultSecrets returns a AzureKeyVaultSecretInformer.
func (v *version) AzureKeyVaultSecrets() AzureKeyVaultSecretInformer {
	return &azureKeyVaultSecretInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
