/*
Copyright Sparebanken Vest

Authored by The Cumulus Team.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/SparebankenVest/azure-keyvault-controller/pkg/client/clientset/versioned/typed/azurekeyvaultcontroller/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAzurekeyvaultcontrollerV1alpha1 struct {
	*testing.Fake
}

func (c *FakeAzurekeyvaultcontrollerV1alpha1) AzureKeyVaultSecrets(namespace string) v1alpha1.AzureKeyVaultSecretInterface {
	return &FakeAzureKeyVaultSecrets{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAzurekeyvaultcontrollerV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
