/*
Copyright Sparebanken Vest

Based on the Kubernetes controller example at
https://github.com/kubernetes/sample-controller

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/apis/azure/identity/v1beta1"
	scheme "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/client/azure/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AzureManagedIdentitiesGetter has a method to return a AzureManagedIdentityInterface.
// A group's client should implement this interface.
type AzureManagedIdentitiesGetter interface {
	AzureManagedIdentities(namespace string) AzureManagedIdentityInterface
}

// AzureManagedIdentityInterface has methods to work with AzureManagedIdentity resources.
type AzureManagedIdentityInterface interface {
	Create(*v1beta1.AzureManagedIdentity) (*v1beta1.AzureManagedIdentity, error)
	Update(*v1beta1.AzureManagedIdentity) (*v1beta1.AzureManagedIdentity, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.AzureManagedIdentity, error)
	List(opts v1.ListOptions) (*v1beta1.AzureManagedIdentityList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.AzureManagedIdentity, err error)
	AzureManagedIdentityExpansion
}

// azureManagedIdentities implements AzureManagedIdentityInterface
type azureManagedIdentities struct {
	client rest.Interface
	ns     string
}

// newAzureManagedIdentities returns a AzureManagedIdentities
func newAzureManagedIdentities(c *IdentityV1beta1Client, namespace string) *azureManagedIdentities {
	return &azureManagedIdentities{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the azureManagedIdentity, and returns the corresponding azureManagedIdentity object, and an error if there is any.
func (c *azureManagedIdentities) Get(name string, options v1.GetOptions) (result *v1beta1.AzureManagedIdentity, err error) {
	result = &v1beta1.AzureManagedIdentity{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azuremanagedidentities").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AzureManagedIdentities that match those selectors.
func (c *azureManagedIdentities) List(opts v1.ListOptions) (result *v1beta1.AzureManagedIdentityList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.AzureManagedIdentityList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azuremanagedidentities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested azureManagedIdentities.
func (c *azureManagedIdentities) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("azuremanagedidentities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a azureManagedIdentity and creates it.  Returns the server's representation of the azureManagedIdentity, and an error, if there is any.
func (c *azureManagedIdentities) Create(azureManagedIdentity *v1beta1.AzureManagedIdentity) (result *v1beta1.AzureManagedIdentity, err error) {
	result = &v1beta1.AzureManagedIdentity{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("azuremanagedidentities").
		Body(azureManagedIdentity).
		Do().
		Into(result)
	return
}

// Update takes the representation of a azureManagedIdentity and updates it. Returns the server's representation of the azureManagedIdentity, and an error, if there is any.
func (c *azureManagedIdentities) Update(azureManagedIdentity *v1beta1.AzureManagedIdentity) (result *v1beta1.AzureManagedIdentity, err error) {
	result = &v1beta1.AzureManagedIdentity{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azuremanagedidentities").
		Name(azureManagedIdentity.Name).
		Body(azureManagedIdentity).
		Do().
		Into(result)
	return
}

// Delete takes name of the azureManagedIdentity and deletes it. Returns an error if one occurs.
func (c *azureManagedIdentities) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azuremanagedidentities").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *azureManagedIdentities) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azuremanagedidentities").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched azureManagedIdentity.
func (c *azureManagedIdentities) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.AzureManagedIdentity, err error) {
	result = &v1beta1.AzureManagedIdentity{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("azuremanagedidentities").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
