/*
Copyright Sparebanken Vest

Authored by The Cumulus Team.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/SparebankenVest/azure-keyvault-controller/pkg/apis/azurekeyvaultcontroller/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AzureKeyVaultSecretLister helps list AzureKeyVaultSecrets.
type AzureKeyVaultSecretLister interface {
	// List lists all AzureKeyVaultSecrets in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.AzureKeyVaultSecret, err error)
	// AzureKeyVaultSecrets returns an object that can list and get AzureKeyVaultSecrets.
	AzureKeyVaultSecrets(namespace string) AzureKeyVaultSecretNamespaceLister
	AzureKeyVaultSecretListerExpansion
}

// azureKeyVaultSecretLister implements the AzureKeyVaultSecretLister interface.
type azureKeyVaultSecretLister struct {
	indexer cache.Indexer
}

// NewAzureKeyVaultSecretLister returns a new AzureKeyVaultSecretLister.
func NewAzureKeyVaultSecretLister(indexer cache.Indexer) AzureKeyVaultSecretLister {
	return &azureKeyVaultSecretLister{indexer: indexer}
}

// List lists all AzureKeyVaultSecrets in the indexer.
func (s *azureKeyVaultSecretLister) List(selector labels.Selector) (ret []*v1alpha1.AzureKeyVaultSecret, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AzureKeyVaultSecret))
	})
	return ret, err
}

// AzureKeyVaultSecrets returns an object that can list and get AzureKeyVaultSecrets.
func (s *azureKeyVaultSecretLister) AzureKeyVaultSecrets(namespace string) AzureKeyVaultSecretNamespaceLister {
	return azureKeyVaultSecretNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AzureKeyVaultSecretNamespaceLister helps list and get AzureKeyVaultSecrets.
type AzureKeyVaultSecretNamespaceLister interface {
	// List lists all AzureKeyVaultSecrets in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.AzureKeyVaultSecret, err error)
	// Get retrieves the AzureKeyVaultSecret from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.AzureKeyVaultSecret, error)
	AzureKeyVaultSecretNamespaceListerExpansion
}

// azureKeyVaultSecretNamespaceLister implements the AzureKeyVaultSecretNamespaceLister
// interface.
type azureKeyVaultSecretNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AzureKeyVaultSecrets in the indexer for a given namespace.
func (s azureKeyVaultSecretNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.AzureKeyVaultSecret, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AzureKeyVaultSecret))
	})
	return ret, err
}

// Get retrieves the AzureKeyVaultSecret from the indexer for a given namespace and name.
func (s azureKeyVaultSecretNamespaceLister) Get(name string) (*v1alpha1.AzureKeyVaultSecret, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("azurekeyvaultsecret"), name)
	}
	return obj.(*v1alpha1.AzureKeyVaultSecret), nil
}
