/*
Copyright Sparebanken Vest

Authored by The Cumulus Team.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AzureKeyVaultSecretListerExpansion allows custom methods to be added to
// AzureKeyVaultSecretLister.
type AzureKeyVaultSecretListerExpansion interface{}

// AzureKeyVaultSecretNamespaceListerExpansion allows custom methods to be added to
// AzureKeyVaultSecretNamespaceLister.
type AzureKeyVaultSecretNamespaceListerExpansion interface{}
