/*
Copyright Sparebanken Vest

Based on the Kubernetes controller example at
https://github.com/kubernetes/sample-controller

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	"fmt"

	spvv1 "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/client/clientset/versioned/typed/azurekeyvault/v1"
	spvv1alpha1 "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/client/clientset/versioned/typed/azurekeyvault/v1alpha1"
	spvv2alpha1 "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/client/clientset/versioned/typed/azurekeyvault/v2alpha1"
	spvv2beta1 "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/client/clientset/versioned/typed/azurekeyvault/v2beta1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	SpvV1alpha1() spvv1alpha1.SpvV1alpha1Interface
	SpvV1() spvv1.SpvV1Interface
	SpvV2alpha1() spvv2alpha1.SpvV2alpha1Interface
	SpvV2beta1() spvv2beta1.SpvV2beta1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	spvV1alpha1 *spvv1alpha1.SpvV1alpha1Client
	spvV1       *spvv1.SpvV1Client
	spvV2alpha1 *spvv2alpha1.SpvV2alpha1Client
	spvV2beta1  *spvv2beta1.SpvV2beta1Client
}

// SpvV1alpha1 retrieves the SpvV1alpha1Client
func (c *Clientset) SpvV1alpha1() spvv1alpha1.SpvV1alpha1Interface {
	return c.spvV1alpha1
}

// SpvV1 retrieves the SpvV1Client
func (c *Clientset) SpvV1() spvv1.SpvV1Interface {
	return c.spvV1
}

// SpvV2alpha1 retrieves the SpvV2alpha1Client
func (c *Clientset) SpvV2alpha1() spvv2alpha1.SpvV2alpha1Interface {
	return c.spvV2alpha1
}

// SpvV2beta1 retrieves the SpvV2beta1Client
func (c *Clientset) SpvV2beta1() spvv2beta1.SpvV2beta1Interface {
	return c.spvV2beta1
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfig will generate a rate-limiter in configShallowCopy.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		if configShallowCopy.Burst <= 0 {
			return nil, fmt.Errorf("burst is required to be greater than 0 when RateLimiter is not set and QPS is set to greater than 0")
		}
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.spvV1alpha1, err = spvv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.spvV1, err = spvv1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.spvV2alpha1, err = spvv2alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.spvV2beta1, err = spvv2beta1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.spvV1alpha1 = spvv1alpha1.NewForConfigOrDie(c)
	cs.spvV1 = spvv1.NewForConfigOrDie(c)
	cs.spvV2alpha1 = spvv2alpha1.NewForConfigOrDie(c)
	cs.spvV2beta1 = spvv2beta1.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.spvV1alpha1 = spvv1alpha1.New(c)
	cs.spvV1 = spvv1.New(c)
	cs.spvV2alpha1 = spvv2alpha1.New(c)
	cs.spvV2beta1 = spvv2beta1.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
