/*
Copyright Sparebanken Vest

Based on the Kubernetes controller example at
https://github.com/kubernetes/sample-controller

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"time"

	v2alpha1 "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/apis/azurekeyvault/v2alpha1"
	scheme "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AzureKeyVaultSecretIdentitiesGetter has a method to return a AzureKeyVaultSecretIdentityInterface.
// A group's client should implement this interface.
type AzureKeyVaultSecretIdentitiesGetter interface {
	AzureKeyVaultSecretIdentities(namespace string) AzureKeyVaultSecretIdentityInterface
}

// AzureKeyVaultSecretIdentityInterface has methods to work with AzureKeyVaultSecretIdentity resources.
type AzureKeyVaultSecretIdentityInterface interface {
	Create(*v2alpha1.AzureKeyVaultSecretIdentity) (*v2alpha1.AzureKeyVaultSecretIdentity, error)
	Update(*v2alpha1.AzureKeyVaultSecretIdentity) (*v2alpha1.AzureKeyVaultSecretIdentity, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v2alpha1.AzureKeyVaultSecretIdentity, error)
	List(opts v1.ListOptions) (*v2alpha1.AzureKeyVaultSecretIdentityList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v2alpha1.AzureKeyVaultSecretIdentity, err error)
	AzureKeyVaultSecretIdentityExpansion
}

// azureKeyVaultSecretIdentities implements AzureKeyVaultSecretIdentityInterface
type azureKeyVaultSecretIdentities struct {
	client rest.Interface
	ns     string
}

// newAzureKeyVaultSecretIdentities returns a AzureKeyVaultSecretIdentities
func newAzureKeyVaultSecretIdentities(c *AzurekeyvaultV2alpha1Client, namespace string) *azureKeyVaultSecretIdentities {
	return &azureKeyVaultSecretIdentities{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the azureKeyVaultSecretIdentity, and returns the corresponding azureKeyVaultSecretIdentity object, and an error if there is any.
func (c *azureKeyVaultSecretIdentities) Get(name string, options v1.GetOptions) (result *v2alpha1.AzureKeyVaultSecretIdentity, err error) {
	result = &v2alpha1.AzureKeyVaultSecretIdentity{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azurekeyvaultsecretidentities").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AzureKeyVaultSecretIdentities that match those selectors.
func (c *azureKeyVaultSecretIdentities) List(opts v1.ListOptions) (result *v2alpha1.AzureKeyVaultSecretIdentityList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.AzureKeyVaultSecretIdentityList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azurekeyvaultsecretidentities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested azureKeyVaultSecretIdentities.
func (c *azureKeyVaultSecretIdentities) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("azurekeyvaultsecretidentities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a azureKeyVaultSecretIdentity and creates it.  Returns the server's representation of the azureKeyVaultSecretIdentity, and an error, if there is any.
func (c *azureKeyVaultSecretIdentities) Create(azureKeyVaultSecretIdentity *v2alpha1.AzureKeyVaultSecretIdentity) (result *v2alpha1.AzureKeyVaultSecretIdentity, err error) {
	result = &v2alpha1.AzureKeyVaultSecretIdentity{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("azurekeyvaultsecretidentities").
		Body(azureKeyVaultSecretIdentity).
		Do().
		Into(result)
	return
}

// Update takes the representation of a azureKeyVaultSecretIdentity and updates it. Returns the server's representation of the azureKeyVaultSecretIdentity, and an error, if there is any.
func (c *azureKeyVaultSecretIdentities) Update(azureKeyVaultSecretIdentity *v2alpha1.AzureKeyVaultSecretIdentity) (result *v2alpha1.AzureKeyVaultSecretIdentity, err error) {
	result = &v2alpha1.AzureKeyVaultSecretIdentity{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azurekeyvaultsecretidentities").
		Name(azureKeyVaultSecretIdentity.Name).
		Body(azureKeyVaultSecretIdentity).
		Do().
		Into(result)
	return
}

// Delete takes name of the azureKeyVaultSecretIdentity and deletes it. Returns an error if one occurs.
func (c *azureKeyVaultSecretIdentities) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azurekeyvaultsecretidentities").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *azureKeyVaultSecretIdentities) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azurekeyvaultsecretidentities").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched azureKeyVaultSecretIdentity.
func (c *azureKeyVaultSecretIdentities) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v2alpha1.AzureKeyVaultSecretIdentity, err error) {
	result = &v2alpha1.AzureKeyVaultSecretIdentity{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("azurekeyvaultsecretidentities").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
