{{ $ca := genCA "svc-cat-ca" 3650 }}
{{ $svcName := include "azure-key-vault-webhook.fullname" . }}
{{ $cn := printf "%s.%s.svc" $svcName .Release.Namespace }}
{{ $server := genSignedCert $cn nil nil 365 $ca }}

apiVersion: v1
kind: List
metadata:
items:

- apiVersion: v1
  kind: Secret
  metadata:
    name: {{ template "azure-key-vault-webhook.fullname" . }}
  data:
    servingCert: {{ b64enc $server.Cert }}
    servingKey: {{ b64enc $server.Key }}
    caCert: {{ b64enc $ca.Cert }}

- apiVersion: admissionregistration.k8s.io/v1beta1
  kind: MutatingWebhookConfiguration
  metadata:
    name: {{ template "azure-key-vault-webhook.fullname" . }}
  webhooks:
  - name: pods.{{ template "azure-key-vault-webhook.name" . }}.admission.spv.no
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ template "azure-key-vault-webhook.fullname" . }}
        path: /pods
      caBundle: {{ b64enc $ca.Cert }}
    rules:
    - operations:
      - CREATE
      apiGroups:
      - "*"
      apiVersions:
      - "*"
      resources:
      - pods
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
      - key: name
        operator: NotIn
        values:
        - {{ .Release.Namespace }}
