---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "azure-key-vault-controller.fullname" . }}
  labels:
    app: {{ template "azure-key-vault-controller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "azure-key-vault-controller.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "azure-key-vault-controller.name" . }}
        release: {{ .Release.Name }}
        {{- if and .Values.keyVault.customAuth.enabled .Values.keyVault.customAuth.podIdentitySelector}}
        aadpodidbinding: {{ .Values.keyVault.customAuth.podIdentitySelector }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "azure-key-vault-controller.fullname" . }}
      containers:
      - name: azure-keyvault-controller
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        args:
          - "--cloudconfig={{ .Values.cloudConfig }}"
        env:
        - name: AZURE_VAULT_NORMAL_POLL_INTERVALS
          value: "{{ .Values.keyVault.polling.normalInterval }}"
        - name: AZURE_VAULT_EXCEPTION_POLL_INTERVALS
          value: "{{ .Values.keyVault.polling.failureInterval }}"
        - name: AZURE_VAULT_MAX_FAILURE_ATTEMPTS
          value: "{{ .Values.keyVault.polling.failureAttempts }}"
        - name: AAD_POD_BINDING_LABEL
          valueFrom:
            fieldRef:
              fieldPath:  metadata.labels['aadpodidbinding']
        - name: CUSTOM_AUTH
          value: {{ .Values.keyVault.customAuth.enabled | quote }}
        - name: LOG_LEVEL
          value: "{{ .Values.logLevel }}"
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value }}
        {{- end }}
        volumeMounts:
          - name: azure-config
            mountPath: "{{ .Values.cloudConfig }}"
            readOnly: true
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.image.pullSecret }}"
      {{- end }}
      volumes:
      - name: azure-config
        hostPath:
          path: "{{ .Values.cloudConfig }}"
          type: File
