/*
Copyright Sparebanken Vest

Based on the Kubernetes controller example at
https://github.com/kubernetes/sample-controller

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	keyvaultv1 "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/apis/azure/keyvault/v1"
	versioned "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v1 "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/client/listers/keyvault/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AzureKeyVaultSecretInformer provides access to a shared informer and lister for
// AzureKeyVaultSecrets.
type AzureKeyVaultSecretInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.AzureKeyVaultSecretLister
}

type azureKeyVaultSecretInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAzureKeyVaultSecretInformer constructs a new informer for AzureKeyVaultSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAzureKeyVaultSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAzureKeyVaultSecretInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAzureKeyVaultSecretInformer constructs a new informer for AzureKeyVaultSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAzureKeyVaultSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KeyvaultV1().AzureKeyVaultSecrets(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KeyvaultV1().AzureKeyVaultSecrets(namespace).Watch(options)
			},
		},
		&keyvaultv1.AzureKeyVaultSecret{},
		resyncPeriod,
		indexers,
	)
}

func (f *azureKeyVaultSecretInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAzureKeyVaultSecretInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *azureKeyVaultSecretInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&keyvaultv1.AzureKeyVaultSecret{}, f.defaultInformer)
}

func (f *azureKeyVaultSecretInformer) Lister() v1.AzureKeyVaultSecretLister {
	return v1.NewAzureKeyVaultSecretLister(f.Informer().GetIndexer())
}
