/*
Copyright Sparebanken Vest

Based on the Kubernetes controller example at
https://github.com/kubernetes/sample-controller

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/apis/azureidentity/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAzureManagedIdentities implements AzureManagedIdentityInterface
type FakeAzureManagedIdentities struct {
	Fake *FakeAzureidentityV1beta1
	ns   string
}

var azuremanagedidentitiesResource = schema.GroupVersionResource{Group: "azureidentity.spv.no", Version: "v1beta1", Resource: "azuremanagedidentities"}

var azuremanagedidentitiesKind = schema.GroupVersionKind{Group: "azureidentity.spv.no", Version: "v1beta1", Kind: "AzureManagedIdentity"}

// Get takes name of the azureManagedIdentity, and returns the corresponding azureManagedIdentity object, and an error if there is any.
func (c *FakeAzureManagedIdentities) Get(name string, options v1.GetOptions) (result *v1beta1.AzureManagedIdentity, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(azuremanagedidentitiesResource, c.ns, name), &v1beta1.AzureManagedIdentity{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AzureManagedIdentity), err
}

// List takes label and field selectors, and returns the list of AzureManagedIdentities that match those selectors.
func (c *FakeAzureManagedIdentities) List(opts v1.ListOptions) (result *v1beta1.AzureManagedIdentityList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(azuremanagedidentitiesResource, azuremanagedidentitiesKind, c.ns, opts), &v1beta1.AzureManagedIdentityList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.AzureManagedIdentityList{ListMeta: obj.(*v1beta1.AzureManagedIdentityList).ListMeta}
	for _, item := range obj.(*v1beta1.AzureManagedIdentityList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested azureManagedIdentities.
func (c *FakeAzureManagedIdentities) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(azuremanagedidentitiesResource, c.ns, opts))

}

// Create takes the representation of a azureManagedIdentity and creates it.  Returns the server's representation of the azureManagedIdentity, and an error, if there is any.
func (c *FakeAzureManagedIdentities) Create(azureManagedIdentity *v1beta1.AzureManagedIdentity) (result *v1beta1.AzureManagedIdentity, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(azuremanagedidentitiesResource, c.ns, azureManagedIdentity), &v1beta1.AzureManagedIdentity{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AzureManagedIdentity), err
}

// Update takes the representation of a azureManagedIdentity and updates it. Returns the server's representation of the azureManagedIdentity, and an error, if there is any.
func (c *FakeAzureManagedIdentities) Update(azureManagedIdentity *v1beta1.AzureManagedIdentity) (result *v1beta1.AzureManagedIdentity, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(azuremanagedidentitiesResource, c.ns, azureManagedIdentity), &v1beta1.AzureManagedIdentity{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AzureManagedIdentity), err
}

// Delete takes name of the azureManagedIdentity and deletes it. Returns an error if one occurs.
func (c *FakeAzureManagedIdentities) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(azuremanagedidentitiesResource, c.ns, name), &v1beta1.AzureManagedIdentity{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAzureManagedIdentities) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(azuremanagedidentitiesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.AzureManagedIdentityList{})
	return err
}

// Patch applies the patch and returns the patched azureManagedIdentity.
func (c *FakeAzureManagedIdentities) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.AzureManagedIdentity, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(azuremanagedidentitiesResource, c.ns, name, pt, data, subresources...), &v1beta1.AzureManagedIdentity{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AzureManagedIdentity), err
}
