apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: azurekeyvaultsecrets.spv.no
spec:
  group: spv.no
  names:
    kind: AzureKeyVaultSecret
    listKind: AzureKeyVaultSecretList
    plural: azurekeyvaultsecrets
    singular: azurekeyvaultsecret
    shortNames:
    - akvs
    categories:
    - all
  additionalPrinterColumns:
    - name: Secret Name
      type: string
      description: Which Kubernetes Secret this resource is synched with
      JSONPath: .status.secretName
    - name: Vault
      type: string
      description: Which Azure Key Vault this resource is synched with
      JSONPath: .spec.vault.name
    - name: Vault Object
      type: string
      description: Which Azure Key Vault object this resource is synched with
      JSONPath: .spec.vault.object.name
    - name: Synched
      type: string
      description: When this resource was last synched with Azure Key Vault
      JSONPath: .status.lastAzureUpdate
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required: ['vault']
          properties:
            vault:
              required: ['name', 'object']
              properties:
                name:
                  type: string
                  description: Name of the Azure Key Vault
                object:
                  required: ['name', 'type']
                  properties:
                    name:
                      type: string
                      description: The object name in Azure Key Vault
                    type:
                      type: string
                      description: The type of object in Azure Key Vault
                      enum:
                      - secret
                      - multi-key-value-secret # not implemented
                      - certificate
                      - exportable-certificate
                      - key # not implemented
                      - base64-encoded-secret
                    version:
                      type: string
                      description: The object version in Azure Key Vault
            output:
              properties:
                secret:
                  properties:
                    name:
                      type: string
                      description: Name for Kubernetes secret - default is name of this resource (metadata.name)
                    type:
                      type: string
                      description: Type of Secret in Kubernetes
                    dataKey:
                      type: string
                      description: The key to use in Kubernetes secret when setting the value from Azure Keyv Vault object data
