name: 'Push'
description: 'Push containers to Docker registry'
inputs:
  push-make-action:  
    description: 'Action in makefile to push package to docker repo'
    required: true
  docker-user:  
    description: 'Username to authenticate with docker repository'
    required: true
  docker-passw:  
    description: 'Password to authenticate with docker repository'
    required: true
  
runs:
  using: "composite"
  steps: 
    - name: Push images to private repo
      run: |
        echo "${{ inputs.docker-passw}}" | docker login -u ${{ inputs.docker-user }} --password-stdin dokken.azurecr.io
        make ${{ inputs.push-make-action }}
      shell: bash  
