---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azurekeyvaultsecrets.spv.no
spec:
  group: spv.no
  names:
    categories:
    - all
    kind: AzureKeyVaultSecret
    listKind: AzureKeyVaultSecretList
    plural: azurekeyvaultsecrets
    shortNames:
    - akvs
    singular: azurekeyvaultsecret
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Which Azure Key Vault this resource is asosiated with
      jsonPath: .spec.vault.name
      name: Vault
      type: string
    - description: Which Azure Key Vault object this resource is asosiated with
      jsonPath: .spec.vault.object.name
      name: Vault Object
      type: string
    - description: Which Kubernetes Secret this resource is synched with, if any
      jsonPath: .status.secretName
      name: Secret Name
      type: string
    - description: When this resource was last synched with Azure Key Vault
      jsonPath: .status.lastAzureUpdate
      name: Synched
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              output:
                properties:
                  secret:
                    properties:
                      chainOrder:
                        description: By setting chainOrder to ensureserverfirst the server certificate will be moved first in the chain
                        enum:
                        - ensureserverfirst
                        type: string
                      dataKey:
                        description: The key to use in Kubernetes secret when setting the value from Azure Keyv Vault object data
                        type: string
                      name:
                        description: Name for Kubernetes secret
                        type: string
                      type:
                        description: Type of Secret in Kubernetes
                        type: string
                    required:
                    - name
                    type: object
                  transform:
                    items:
                      type: string
                    type: array
                type: object
              vault:
                properties:
                  name:
                    description: Name of the Azure Key Vault
                    type: string
                  object:
                    properties:
                      contentType:
                        description: Only used when type is multi-key-value-secret.
                        enum:
                        - application/x-json
                        - application/x-yaml
                        type: string
                      name:
                        description: The object name in Azure Key Vault
                        type: string
                      type:
                        description: The type of object in Azure Key Vault
                        enum:
                        - secret
                        - certificate
                        - key
                        - multi-key-value-secret
                        type: string
                      version:
                        description: The object version in Azure Key Vault
                        type: string
                    required:
                    - name
                    - type
                    type: object
                required:
                - name
                - object
                type: object
            required:
            - vault
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - additionalPrinterColumns:
    - description: Which Azure Key Vault this resource is asosiated with
      jsonPath: .spec.vault.name
      name: Vault
      type: string
    - description: Which Azure Key Vault object this resource is asosiated with
      jsonPath: .spec.vault.object.name
      name: Vault Object
      type: string
    - description: Which Kubernetes Secret or ConfigMap this resource is synched with, if any
      jsonPath: .status.secretName
      name: Output Object
      type: string
    - description: When this resource was last synched with Azure Key Vault
      jsonPath: .status.lastAzureUpdate
      name: Synched
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              output:
                properties:
                  secret:
                    properties:
                      dataKey:
                        description: The key to use in Kubernetes secret when setting the value from Azure Keyv Vault object data
                        type: string
                      name:
                        description: Name for Kubernetes secret
                        type: string
                      type:
                        description: Type of Secret in Kubernetes
                        type: string
                    required:
                    - name
                    type: object
                  transform:
                    items:
                      type: string
                    type: array
                type: object
              vault:
                properties:
                  name:
                    description: Name of the Azure Key Vault
                    type: string
                  object:
                    properties:
                      contentType:
                        description: Only used when type is multi-key-value-secret.
                        enum:
                        - application/x-json
                        - application/x-yaml
                        type: string
                      name:
                        description: The object name in Azure Key Vault
                        type: string
                      type:
                        description: The type of object in Azure Key Vault
                        enum:
                        - secret
                        - certificate
                        - key
                        - multi-key-value-secret
                        type: string
                      version:
                        description: The object version in Azure Key Vault
                        type: string
                    required:
                    - name
                    - type
                    type: object
                required:
                - name
                - object
                type: object
            required:
            - vault
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - additionalPrinterColumns:
    - description: Which Azure Key Vault this resource is asosiated with
      jsonPath: .spec.vault.name
      name: Vault
      type: string
    - description: Which Azure Key Vault object this resource is asosiated with
      jsonPath: .spec.vault.object.name
      name: Vault Object
      type: string
    - description: Which Kubernetes Secret this resource is synched with, if any
      jsonPath: .status.secretName
      name: Secret Name
      type: string
    - description: Which Kubernetes ConfigMap this resource is synched with, if any
      jsonPath: .status.configMapName
      name: ConfigMap Name
      type: string
    - description: When this resource was last synched with Azure Key Vault
      jsonPath: .status.lastAzureUpdate
      name: Last Synched
      type: date
    name: v2alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              output:
                properties:
                  configMap:
                    properties:
                      dataKey:
                        description: The key to use in Kubernetes ConfigMap when setting the value from Azure Keyv Vault object data
                        type: string
                      name:
                        description: Name for Kubernetes ConfigMap
                        type: string
                    required:
                    - name
                    type: object
                  secret:
                    properties:
                      chainOrder:
                        description: By setting chainOrder to ensureserverfirst the server certificate will be moved first in the chain
                        enum:
                        - ensureserverfirst
                        type: string
                      dataKey:
                        description: The key to use in Kubernetes secret when setting the value from Azure Keyv Vault object data
                        type: string
                      name:
                        description: Name for Kubernetes secret
                        type: string
                      type:
                        description: Type of Secret in Kubernetes
                        type: string
                    required:
                    - name
                    type: object
                  transform:
                    items:
                      type: string
                    type: array
                type: object
              vault:
                properties:
                  azureIdentity:
                    properties:
                      name:
                        description: Name of the azureIdentity to use for Azure Key Vault authentication
                        type: string
                    type: object
                  name:
                    description: Name of the Azure Key Vault
                    type: string
                  object:
                    properties:
                      contentType:
                        description: Only used when type is multi-key-value-secret.
                        enum:
                        - application/x-json
                        - application/x-yaml
                        type: string
                      name:
                        description: The object name in Azure Key Vault
                        type: string
                      type:
                        description: The type of object in Azure Key Vault
                        enum:
                        - secret
                        - certificate
                        - key
                        - multi-key-value-secret
                        type: string
                      version:
                        description: The object version in Azure Key Vault
                        type: string
                    required:
                    - name
                    - type
                    type: object
                required:
                - name
                - object
                type: object
            required:
            - vault
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - additionalPrinterColumns:
    - description: Which Azure Key Vault this resource is asosiated with
      jsonPath: .spec.vault.name
      name: Vault
      type: string
    - description: Which Azure Key Vault object this resource is asosiated with
      jsonPath: .spec.vault.object.name
      name: Vault Object
      type: string
    - description: Which Kubernetes Secret this resource is synched with, if any
      jsonPath: .status.secretName
      name: Secret Name
      type: string
    - description: Which Kubernetes ConfigMap this resource is synched with, if any
      jsonPath: .status.configMapName
      name: ConfigMap Name
      type: string
    - description: When this resource was last synched with Azure Key Vault
      jsonPath: .status.lastAzureUpdate
      name: Last Synched
      type: date
    name: v2beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              output:
                properties:
                  configMap:
                    properties:
                      dataKey:
                        description: The key to use in Kubernetes ConfigMap when setting the value from Azure Keyv Vault object data
                        type: string
                      name:
                        description: Name for Kubernetes ConfigMap
                        type: string
                    required:
                    - name
                    type: object
                  secret:
                    properties:
                      chainOrder:
                        description: By setting chainOrder to ensureserverfirst the server certificate will be moved first in the chain
                        enum:
                        - ensureserverfirst
                        type: string
                      dataKey:
                        description: The key to use in Kubernetes secret when setting the value from Azure Keyv Vault object data
                        type: string
                      name:
                        description: Name for Kubernetes secret
                        type: string
                      type:
                        description: Type of Secret in Kubernetes
                        type: string
                    required:
                    - name
                    type: object
                  transform:
                    items:
                      type: string
                    type: array
                type: object
              vault:
                properties:
                  azureIdentity:
                    properties:
                      name:
                        description: Name of the azureIdentity to use for Azure Key Vault authentication
                        type: string
                    type: object
                  name:
                    description: Name of the Azure Key Vault
                    type: string
                  object:
                    properties:
                      contentType:
                        description: Only used when type is multi-key-value-secret.
                        enum:
                        - application/x-json
                        - application/x-yaml
                        type: string
                      name:
                        description: The object name in Azure Key Vault
                        type: string
                      type:
                        description: The type of object in Azure Key Vault
                        enum:
                        - secret
                        - certificate
                        - key
                        - multi-key-value-secret
                        type: string
                      version:
                        description: The object version in Azure Key Vault
                        type: string
                    required:
                    - name
                    - type
                    type: object
                required:
                - name
                - object
                type: object
            required:
            - vault
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
