apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: azurekeyvaultsecrets.spv.no
  labels:
    app.kubernetes.io/name: akv2k8s
  annotations:
    "helm.sh/resource-policy": keep
spec:
  group: spv.no
  names:
    kind: AzureKeyVaultSecret
    listKind: AzureKeyVaultSecretList
    plural: azurekeyvaultsecrets
    singular: azurekeyvaultsecret
    shortNames:
    - akvs
    categories:
    - all
  additionalPrinterColumns:
    - name: Vault
      type: string
      description: Which Azure Key Vault this resource is asosiated with
      JSONPath: .spec.vault.name
    - name: Vault Object
      type: string
      description: Which Azure Key Vault object this resource is asosiated with
      JSONPath: .spec.vault.object.name
    - name: Secret Name
      type: string
      description: Which Kubernetes Secret this resource is synched with, if any
      JSONPath: .status.secretName
    - name: Synched
      type: string
      description: When this resource was last synched with Azure Key Vault
      JSONPath: .status.lastAzureUpdate
  scope: Namespaced
  versions: 
    - name: v1alpha1
      served: true
      storage: true
    - name: v1
      served: true
      storage: false
      
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required: ['vault']
          properties:
            vault:
              required: ['name', 'object']
              properties:
                name:
                  type: string
                  description: Name of the Azure Key Vault
                object:
                  required: ['name', 'type']
                  properties:
                    name:
                      type: string
                      description: The object name in Azure Key Vault
                    type:
                      type: string
                      description: The type of object in Azure Key Vault
                      enum:
                      - secret
                      - certificate
                      - key
                      - multi-key-value-secret 
                    version:
                      type: string
                      description: The object version in Azure Key Vault
                    contentType:
                      type: string
                      description: Only used when type is multi-key-value-secret. 
                      enum:
                      - application/x-json
                      - application/x-yaml
            output:
              properties:
                transform:
                  type: array
                  items:
                    type: string
                secret:
                  required: ['name']
                  properties:
                    name:
                      type: string
                      description: Name for Kubernetes secret
                    type:
                      type: string
                      description: Type of Secret in Kubernetes
                    dataKey:
                      type: string
                      description: The key to use in Kubernetes secret when setting the value from Azure Keyv Vault object data
