apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: db-config
  namespace: akv-test
spec:
  vault:
    name: akv2k8sinttestskv
    object:
      contentType: application/x-json # make sure this matches the content of the secret, can be either 'application/x-json' or 'application/x-yaml'
      name: akv2k8s-multi-key-test
      type: multi-key-value-secret
  output:
    secret:
      name: db-config
