/*
Copyright Sparebanken Vest

Based on the Kubernetes controller example at
https://github.com/kubernetes/sample-controller

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	azureidentityv1beta1 "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/apis/azureidentity/v1beta1"
	versioned "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/SparebankenVest/azure-key-vault-to-kubernetes/pkg/k8s/client/listers/azureidentity/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AzureManagedIdentityInformer provides access to a shared informer and lister for
// AzureManagedIdentities.
type AzureManagedIdentityInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.AzureManagedIdentityLister
}

type azureManagedIdentityInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAzureManagedIdentityInformer constructs a new informer for AzureManagedIdentity type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAzureManagedIdentityInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAzureManagedIdentityInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAzureManagedIdentityInformer constructs a new informer for AzureManagedIdentity type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAzureManagedIdentityInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzureidentityV1beta1().AzureManagedIdentities(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzureidentityV1beta1().AzureManagedIdentities(namespace).Watch(options)
			},
		},
		&azureidentityv1beta1.AzureManagedIdentity{},
		resyncPeriod,
		indexers,
	)
}

func (f *azureManagedIdentityInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAzureManagedIdentityInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *azureManagedIdentityInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&azureidentityv1beta1.AzureManagedIdentity{}, f.defaultInformer)
}

func (f *azureManagedIdentityInformer) Lister() v1beta1.AzureManagedIdentityLister {
	return v1beta1.NewAzureManagedIdentityLister(f.Informer().GetIndexer())
}
