name: build and deploy to private repo

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'docs/**'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Golang
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.4'

    - name: Test
      run: make test

    - name: Create Docker Image
      run: make build

    - name: Docker Login
      run: docker login -u ${{secrets.PRIVATE_REGISTRY_USERNAME}} -p ${{secrets.PRIVATE_REGISTRY_PASSWORD}} dokken.azurecr.io

    - name: Push Docker Image
      run: make push
        